version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12
    branches:
      only:
        - main
    steps:
      - add_ssh_keys:
          fingerprints:
            - "e2:a7:b8:0b:05:6c:ac:49:cc:7d:9b:14:29:7c:65:95"
      - checkout

      - restore_cache:
          keys:
            - dependy-winsonye

      - run:
          name: Install
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: dependy-winsonye

      - run:
          name: Build
          command: npm run build

      - run:
          name: prepare shell commands
          command: chmod +x scripts/deploy.sh

      - run:
          name: run deploy to github pages
          command: ./scripts/deploy.sh
# version: 2
# jobs:
#   build:
#     docker:
#       - image: circleci/node:12
#     branches:
#       only:
#         - main
#     steps:
#       - add_ssh_keys:
#           fingerprints:
#             - "46:57:e9:55:14:5a:4b:e3:b5:ba:7b:03:fb:15:a1:88"

#       - checkout

#       - restore_cache:
#           keys:
#             - dependy-winsonye

#       - run:
#           name: Install
#           command: npm install

#       - save_cache:
#           paths:
#             - node_modules
#           key: dependy-winsonye

#       - run:
#           name: Build
#           command: npm run build

#       - run:
#           name: prepare shell commands
#           command: chmod +x scripts/deploy.sh

#       - run:
#           name: run deploy to github pages
#           command: ./scripts/deploy.sh
